# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-release-helm

on:
  push:
    tags:
      - 'helm-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare-build:
    name: Prepare Build
    outputs:
      release_tag: ${{ steps.resolve.outputs.release_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Resolve release tag
        id: resolve
        run: |
          echo "release_tag=$(echo ${GITHUB_REF#refs/*/} | sed 's/^helm-//')" >> $GITHUB_OUTPUT

  release:
    name: Release Helm charts
    needs: [ prepare-build ]
    if: ${{ needs.prepare-build.outputs.release_tag != '' }}
    uses: ./.github/workflows/reusable-helm-release.yaml
    permissions:
      contents: 'read'
      packages: 'write'
      attestations: 'write'
    with:
      registry: ghcr.io/agntcy/telemetry-hub
      release_tag: ${{ needs.prepare-build.outputs.release_tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test-integration:
    name: Run integration tests
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Trigger CSIT integration CI
        uses: ./.github/actions/trigger-integrations
        with:
          github-token: ${{ secrets.AGNTCY_BUILD_BOT_GH_TOKEN }}
